### ISSUE TITLE
DGN Slides

### ISSUE THREAD

**Issue by leipnerm** [fmicompbio/adv_singlecell_2022#19]
Thanks again for the extremely well organized course and fantastic content last month. I was reviewing the added slide decks here and noticed there is no link for the DGN slides. In case it was missing somehow, the link provided during the course was: https://drive.google.com/file/d/1vrsoKBACswM1z6Bl1rvPWm0Phe7nRpWz/view

Best!
Matt

**Comment by ppapasaikas** [comment]
Thanks Matt,
For completion I also uploaded the slides on the repo inside the corresponding folder.

Best,
Pan
